name: CI

on:
  push:
    branches: [ Adity20-patch-1 ]
  pull_request:
    branches: [ Aditya20-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a script
      run: echo "Hello, world!"
